//! Vendored SCIP protobuf types, generated by prost-build from the official
//! `proto/scip.proto` at build time (issues.md #229).
//!
//! Replaces the runtime `scip` + `protobuf` crates: identical wire format (the
//! schema is the same v0.8.1 `scip.proto` the `scip` crate was generated from),
//! but no Google protobuf reflection runtime linked into the binary. The types
//! are plain `prost::Message` structs with `pub` fields, decoded via
//! [`prost::Message::decode`].
//!
//! Only the messages `scip_overlay` reads are re-exported (`Index`, `Document`,
//! `Occurrence`, `Metadata`); the rest of the schema is compiled but kept under
//! the raw `scip` module for completeness.

/// Raw generated module — all SCIP messages/enums from `proto/scip.proto`.
pub mod scip {
    include!(concat!(env!("OUT_DIR"), "/scip.rs"));
}

pub use scip::{Document, Index, Metadata, Occurrence};
