//! SCIP protobuf → prost migration characterization (issues.md #229).
//!
//! `scip_overlay.rs` decodes `.scip` files emitted by real compiler-backed
//! indexers (rust-analyzer, scip-go, scip-typescript, …) — bytes produced by
//! non-Rust protoc encoders. This test pins that our decoder reads such bytes
//! back to the right field values, and is the safety net for swapping the
//! runtime `scip` + `protobuf` crates for prost types generated from the
//! vendored `proto/scip.proto`.
//!
//! The fixture `tests/fixtures/scip/sample.scip` is canonical protobuf wire
//! format, generated by rust-protobuf 3.7.2 (the encoder the `scip` crate
//! shipped with). After the prost swap the SAME bytes are decoded by prost and
//! must yield the SAME field values — i.e. old-encoder bytes round-trip through
//! the new decoder identically. This guards the cross-encoder decode path that
//! the in-module round-trip tests (which encode + decode with the same library)
//! cannot reach.

use groundgraph_engine::scip_overlay::parse_index;
use std::path::Path;

fn fixture_path() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/scip/sample.scip")
}

/// Re-generate the committed fixture from the canonical in-memory index using
/// the prost encoder. Ignored by default; run with `cargo test -p
/// groundgraph-engine --test scip_proto_compat -- --ignored
/// regenerate_sample_fixture` after intentionally changing the fixture shape.
///
/// prost and rust-protobuf emit byte-identical wire format for this index, so
/// regenerating under prost reproduces the same bytes the original (rust-protobuf
/// 3.7.2) fixture commit holds — the on-disk fixture is NOT regenerated as part
/// of the normal test run, keeping it anchored to the pre-#229 encoder as the
/// cross-decoder proof.
#[test]
#[ignore = "fixture regen only — run with --ignored"]
fn regenerate_sample_fixture() {
    use groundgraph_engine::scip_proto::{Document, Index, Metadata, Occurrence};
    use prost::Message;

    let metadata = Metadata {
        project_root: "file:///repo/asc-cli".into(),
        ..Default::default()
    };
    let occ = |line0: i32, symbol: &str, roles: i32| Occurrence {
        range: vec![line0, 0, line0, 12],
        symbol: symbol.into(),
        symbol_roles: roles,
        ..Default::default()
    };
    const RUN: &str = "scip-go gomod demo 0.1.0 demo/Svc#run().";
    let index = Index {
        metadata: Some(metadata),
        documents: vec![
            Document {
                relative_path: "b.go".into(),
                occurrences: vec![occ(4, RUN, 0x1)], // definition
                ..Default::default()
            },
            Document {
                relative_path: "a.go".into(),
                occurrences: vec![
                    occ(9, RUN, 0),  // reference (no role)
                    occ(14, RUN, 0), // second call site
                ],
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    let bytes = index.encode_to_vec();
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/scip");
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("sample.scip"), &bytes).unwrap();
    eprintln!(
        "wrote {} bytes to {}",
        bytes.len(),
        fixture_path().display()
    );
}

/// Decode the committed fixture and assert every field `scip_overlay` reads.
/// The assertions are written against field *names* that are identical across
/// the rust-protobuf and prost generated types, so this test passes both before
/// and after the #229 swap and is the byte-level proof that prost decodes
/// old-encoder bytes to the same values.
#[test]
fn decodes_real_wire_format_fixture_to_expected_fields() {
    let bytes =
        std::fs::read(fixture_path()).expect("fixture missing — run the ignored regen once");

    let index = parse_index(&bytes).expect("decode fixture");

    assert_eq!(index.documents.len(), 2);
    assert_eq!(index.documents[0].relative_path, "b.go");
    assert_eq!(index.documents[1].relative_path, "a.go");

    // metadata.project_root survives (used to rebase sub-module paths).
    assert_eq!(
        index.metadata.as_ref().unwrap().project_root,
        "file:///repo/asc-cli"
    );

    // Definition occurrence: symbol_roles carries the Definition bit (0x1).
    let def = &index.documents[0].occurrences[0];
    assert_eq!(def.symbol, "scip-go gomod demo 0.1.0 demo/Svc#run().");
    assert!(
        def.symbol_roles & 0x1 != 0,
        "Definition role bit must be set"
    );
    assert_eq!(def.range, vec![4, 0, 4, 12]);

    // Reference occurrences: no Definition role, two distinct call sites.
    let refs = &index.documents[1].occurrences;
    assert_eq!(refs.len(), 2);
    assert!(
        refs.iter().all(|o| o.symbol_roles & 0x1 == 0),
        "references must not carry the Definition role"
    );
    assert_eq!(refs[0].range[0], 9);
    assert_eq!(refs[1].range[0], 14);
}
