//! P9 — AI-authored business-logic candidates.
//!
//! Where the P6.x / P7 / P8 layers produce *code facts* (calls,
//! references, reads_provider, persists_to, …), the P9 layer produces
//! *business claims* — sentences like "PaywallScreen completes a
//! purchase by listening to a stream, calling ProNotifier.applyPurchase,
//! and persisting the entitlement to Hive." The claim is generated by
//! an LLM (today: Claude, acting as the LLM in this work session) and
//! reviewed by a human.
//!
//! Storage shape: a single YAML document at
//! `.specslice/candidates/business_logic.yaml`. Each candidate carries:
//!
//! - `id`: stable slug, used as the `business_candidate::<id>` node id.
//! - `name`: short human-readable title.
//! - `description`: one or two sentences in the analyst's own words.
//! - `evidence`: list of code facts (ArtifactId references) that the
//!   AI considered when proposing the candidate. Each entry resolves
//!   to a node (file/class/method/provider/route/storage) — the engine
//!   then materialises `derives_from` edges from the candidate node to
//!   each evidence node.
//! - `confidence`: 0.0..=1.0, surfaced as the edge's confidence in the
//!   graph.
//! - `open_questions`: list of free-form strings flagging things the AI
//!   could not verify (e.g. "is receipt verification handled
//!   server-side?"). Surfaced in the graph as the candidate node's
//!   `rationale`.
//! - `status`: `proposed` (AI suggested), `confirmed` (human accepted),
//!   `rejected` (human rejected). The engine never writes these — only
//!   the loader reads them.
//!
//! Loading is read-only; the engine never mutates the YAML. The graph
//! view picks the document up via [`load_business_candidates`] and
//! merges its candidates / evidence edges into the in-memory model
//! before applying focus / view filters.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Schema version embedded in every YAML file. Bump only on incompatible
/// changes — readers must accept older minor versions.
pub const BUSINESS_CANDIDATES_SCHEMA_VERSION: u32 = 1;

/// Relative path under the repo root.
pub const BUSINESS_CANDIDATES_REL_PATH: &str = ".specslice/candidates/business_logic.yaml";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct BusinessCandidatesDocument {
    #[serde(default)]
    pub schema_version: u32,
    #[serde(default)]
    pub candidates: Vec<BusinessCandidate>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct BusinessCandidate {
    /// Stable slug — must match `^[a-z0-9][a-z0-9_-]*$`. Used as the
    /// `business_candidate::<id>` node id, so changing the slug renames
    /// the node and breaks any cross-references.
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    /// Each entry is the artifact id of a code fact the AI cited. Lines
    /// that the engine cannot resolve are surfaced as findings instead
    /// of failing the load.
    #[serde(default)]
    pub evidence: Vec<String>,
    /// Optional `(low..=high)` confidence; defaults to `0.5` when
    /// missing so a missing field doesn't silently look like high
    /// confidence.
    #[serde(default)]
    pub confidence: Option<f32>,
    #[serde(default)]
    pub open_questions: Vec<String>,
    /// `proposed` (AI), `confirmed` (human), `rejected` (human). Other
    /// values are treated as `proposed`.
    #[serde(default = "default_status")]
    pub status: String,
}

fn default_status() -> String {
    "proposed".into()
}

/// Outcome of trying to load business candidates from a repository.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoadOutcome {
    pub document: BusinessCandidatesDocument,
    /// Path the document was loaded from (for diagnostics / surfacing).
    pub path: PathBuf,
    /// Soft warnings: invalid IDs, missing required fields, etc. The
    /// engine never panics on bad candidates — it drops them and keeps
    /// going.
    pub warnings: Vec<String>,
}

/// Try to load the candidates document. If the file is missing we
/// return a default outcome with an empty list — P9 is opt-in and
/// repos without one should keep working unchanged.
pub fn load_business_candidates(repo_root: &Path) -> Result<LoadOutcome> {
    let path = repo_root.join(BUSINESS_CANDIDATES_REL_PATH);
    if !path.exists() {
        return Ok(LoadOutcome {
            document: BusinessCandidatesDocument::default(),
            path,
            warnings: Vec::new(),
        });
    }
    let raw = std::fs::read_to_string(&path)
        .with_context(|| format!("reading business candidates from {}", path.display()))?;
    let mut document: BusinessCandidatesDocument = serde_yaml::from_str(&raw)
        .with_context(|| format!("parsing business candidates YAML at {}", path.display()))?;
    let mut warnings = Vec::new();
    // Validate + clean candidates.
    let mut kept: Vec<BusinessCandidate> = Vec::with_capacity(document.candidates.len());
    let mut seen_ids: std::collections::HashSet<String> = std::collections::HashSet::new();
    for c in document.candidates.drain(..) {
        if !is_valid_slug(&c.id) {
            warnings.push(format!(
                "dropping candidate with invalid id `{}` — must match /^[a-z0-9][a-z0-9_-]*$/",
                c.id
            ));
            continue;
        }
        if !seen_ids.insert(c.id.clone()) {
            warnings.push(format!("dropping duplicate candidate id `{}`", c.id));
            continue;
        }
        if c.name.trim().is_empty() {
            warnings.push(format!(
                "dropping candidate `{}` — name must not be empty",
                c.id
            ));
            continue;
        }
        kept.push(c);
    }
    document.candidates = kept;
    Ok(LoadOutcome {
        document,
        path,
        warnings,
    })
}

fn is_valid_slug(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    let bytes = s.as_bytes();
    if !(bytes[0].is_ascii_lowercase() || bytes[0].is_ascii_digit()) {
        return false;
    }
    bytes
        .iter()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || *b == b'_' || *b == b'-')
}

/// Compute the artifact id the engine uses to refer to a candidate
/// node. Kept in one place so callers don't accidentally format it
/// differently in different paths.
pub fn candidate_artifact_id(id: &str) -> String {
    format!("business_candidate::{id}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_returns_empty_when_file_missing() {
        let tmp = tempfile::TempDir::new().unwrap();
        let outcome = load_business_candidates(tmp.path()).unwrap();
        assert!(outcome.document.candidates.is_empty());
        assert!(outcome.warnings.is_empty());
    }

    #[test]
    fn load_parses_full_document() {
        let tmp = tempfile::TempDir::new().unwrap();
        let dir = tmp.path().join(".specslice/candidates");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("business_logic.yaml"),
            r#"
schema_version: 1
candidates:
  - id: complete_purchase
    name: "Completes a purchase and unlocks Pro"
    description: |
      PaywallScreen.listenToPurchaseUpdates calls ProNotifier.applyPurchase
      whenever the purchase stream emits, then persists the entitlement.
    evidence:
      - dart_method::lib/features/paywall/paywall_screen.dart#PaywallScreen.listenToPurchaseUpdates
      - dart_provider::lib/core/settings/pro_provider.dart#proProvider
    confidence: 0.78
    open_questions:
      - "Is receipt verification done server-side?"
    status: proposed
"#,
        )
        .unwrap();

        let outcome = load_business_candidates(tmp.path()).unwrap();
        assert_eq!(outcome.warnings, Vec::<String>::new());
        assert_eq!(outcome.document.candidates.len(), 1);
        let c = &outcome.document.candidates[0];
        assert_eq!(c.id, "complete_purchase");
        assert_eq!(c.evidence.len(), 2);
        assert!((c.confidence.unwrap() - 0.78).abs() < 1e-4);
        assert_eq!(c.open_questions.len(), 1);
    }

    #[test]
    fn invalid_slug_is_dropped_with_warning() {
        let tmp = tempfile::TempDir::new().unwrap();
        let dir = tmp.path().join(".specslice/candidates");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("business_logic.yaml"),
            r#"
candidates:
  - id: "Bad Slug!"
    name: "x"
"#,
        )
        .unwrap();

        let outcome = load_business_candidates(tmp.path()).unwrap();
        assert!(outcome.document.candidates.is_empty());
        assert_eq!(outcome.warnings.len(), 1);
        assert!(outcome.warnings[0].contains("invalid id"));
    }

    #[test]
    fn duplicate_id_drops_second_occurrence() {
        let tmp = tempfile::TempDir::new().unwrap();
        let dir = tmp.path().join(".specslice/candidates");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("business_logic.yaml"),
            r#"
candidates:
  - id: a
    name: First
  - id: a
    name: Second
"#,
        )
        .unwrap();
        let outcome = load_business_candidates(tmp.path()).unwrap();
        assert_eq!(outcome.document.candidates.len(), 1);
        assert_eq!(outcome.document.candidates[0].name, "First");
        assert_eq!(outcome.warnings.len(), 1);
        assert!(outcome.warnings[0].contains("duplicate"));
    }

    #[test]
    fn empty_name_is_dropped() {
        let tmp = tempfile::TempDir::new().unwrap();
        let dir = tmp.path().join(".specslice/candidates");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("business_logic.yaml"),
            r#"
candidates:
  - id: ok
    name: "  "
"#,
        )
        .unwrap();
        let outcome = load_business_candidates(tmp.path()).unwrap();
        assert!(outcome.document.candidates.is_empty());
    }

    #[test]
    fn is_valid_slug_recognises_allowed_and_rejected_shapes() {
        for ok in ["a", "abc", "purchase_flow", "p9-iap", "x1y2"] {
            assert!(is_valid_slug(ok), "{ok} should be valid");
        }
        for bad in ["", " ", "Foo", "_x", "-x", "x y", "z!"] {
            assert!(!is_valid_slug(bad), "{bad} should be invalid");
        }
    }

    #[test]
    fn candidate_artifact_id_uses_business_candidate_prefix() {
        assert_eq!(
            candidate_artifact_id("foo"),
            "business_candidate::foo".to_string()
        );
    }
}
